source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'capybara'
gem 'selenium-webdriver'
gem 'bundler'
gem 'site_prism'
gem 'dbi'
gem 'tiny_tds'
gem 'activerecord-sqlserver-adapter'
gem 'rails'
gem 'execjs'
gem 'date'
gem 'pry'